# Generated by Django 6.0.6 on 2026-07-01 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genesisapp', '0002_contact1_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact1',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
